WebApplication1/Controllers/MovieController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Cinema.DataModels;
using Cinema.Contracts;
using Cinema.Models;
using System;
using System.Collections.Generic;

namespace Cinema.Controllers
{
    public class MovieController : Controller
    {
        private readonly IRepository _repo;
        public MovieController(IRepository repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("EditMovie", new Movie());
        }

        [HttpGet]
        public IActionResult Edit(int movieId)
        {
            var movie = _repo.GetMovieById(movieId);
            return View("EditMovie", movie);
        }

        [HttpPost]
        public IActionResult Save(Movie movie, string producersStr, List<Genre> test)
        {

            if(!ModelState.IsValid)
            {
                return View("EditMovie", movie);
            }

            DateTime releasedate;
            var date = movie.Date?.Trim();
            try
            { 
                releasedate = new DateTime(Convert.ToInt32(date.Substring(6, 4)), Convert.ToInt32(date.Substring(3, 2)), Convert.ToInt32(date.Substring(0, 2)));
                if (releasedate < DateTime.Now)
                    throw new Exception();
            }
            catch
            {
                ModelState.AddModelError("Date", "Entered release date is not valid date");
                return View("EditMovie", movie);
            }

            movie.ReleaseDate = releasedate;
            movie.Genres = movie.Genres.Where(x => x.Selected).ToList();
            
            if(!string.IsNullOrWhiteSpace(producersStr))
            {
                var producers = producersStr.Split(',', StringSplitOptions.RemoveEmptyEntries);
                for(int i = 0; i < producers.Length; ++ i)
                {
                    if(movie.Producers.Any(x => x.Name == producers[i]))
                    {
                        continue;
                    }

                    var prod = _repo.GetProducerIdByName(producers[i].Trim());
                    if (prod == null)
                    {
                        prod = _repo.AddProducer(producers[i].Trim());
                    }

                    movie.Producers.Add(new Producer { Id = (int)prod, Name = producers[i] });
                }
            }

            
            if(movie.Id > 0)
            {
                _repo.UpdateMovie(movie);
            }
            else
            {
                _repo.AddMovie(movie);
            }
            return View("SearchMovies");
        }

        [HttpPost]
        public IActionResult Delete(Movie movie)
        {
            var tickets = _repo.GetMovieTickets(movie.Id);
            foreach(var t in tickets)
            {
                if(t.FK_SubscriptionId != null)
                {
                    _repo.DeleteSubscription((int)t.FK_SubscriptionId);
                }
                _repo.DeleteTicket(t.Id);
            }

            var sessions = _repo.GetSessionsByMovie(movie.Id);
            foreach(var s in sessions)
            {
                _repo.DeleteSession(s.Id);
            }
            _repo.DeleteMovie(movie.Id);
            return View("SearchMovies");
        }

        [HttpGet]
        public IActionResult Search()
        {
            return View("SearchMovies", new SearchMoviesModel());
        }

        [HttpPost]
        public IActionResult Cancel()
        {
            return RedirectToAction("Search");
        }

        [HttpPost]
        public IActionResult Search(SearchMoviesModel model)
        {
            ViewBag.IsAdmin = User.HasClaim("AccessType", "Admin");
            IEnumerable<Movie> movies;
            if (ViewBag.IsAdmin)
            { movies = _repo.GetMoviesByNameGenreOrProducer(model.NameFirstLetters, model.GenreId, model.ProducerId).ToList(); }
            else
            {
                movies = _repo.GetCurrentMovies(DateTime.Now, model.NameFirstLetters, model.GenreId, model.ProducerId).ToList();
            }
            return View("MovieList", movies);
        }
    }
}

WebApplication1/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cinema.Contracts;
using Cinema.DataModels;
using Cinema.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class SessionController : Controller
    {
        private enum TimeAllowance
        {
            Morning = 3,
            Day = 4,
            Evening = 5
        }

        private int GetTimeAllowance(DateTime dateTime)
        {
            if (dateTime.TimeOfDay.Hours < 14)
            {
                return (int)TimeAllowance.Morning;
            }
            else if (dateTime.TimeOfDay.Hours < 18)
            {
                return (int)TimeAllowance.Day;
            }
            return (int)TimeAllowance.Evening;
        }

        IRepository _repository;
        public SessionController(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Add(int movieid)
        {
            return View("AddSession", new Session { MovieId = movieid });
        }

        [HttpPost]
        public IActionResult Save(Session session)
        {
            session.Price = _repository.GetPriceByTimeAllowance(GetTimeAllowance(session.StartTime));
            _repository.AddSession(session);
            return RedirectToAction("Search");
        }

        [HttpGet]
        public IActionResult Search()
        {
            return View("SearchSessions", new SearchSessionsModel());
        }

        [HttpPost]
        public IActionResult Search(SearchSessionsModel searchSessionsModel)
        {
            ViewBag.IsAdmin = User.HasClaim("AccessType", "Admin");
            if(searchSessionsModel.Date == null)
            {
                return View("SessionList", _repository.GetAllSessions());
            }
            return View("SessionList", _repository.GetSessionsByDate(searchSessionsModel.Date.Trim()));
        }

        [HttpGet]
        public IActionResult SearchByFilm(int movieId)
        {
            ViewBag.IsAdmin = User.HasClaim("AccessType", "Admin");
            return View("SessionList", _repository.GetSessionsByMovie(movieId));
        }

        [HttpGet]
        public IActionResult Cancel()
        {
            return RedirectToAction("Search");
        }

        [HttpPost]
        public IActionResult Delete(int sessionid)
        {
            var tickets = _repository.GetSessionTickets(sessionid);
            foreach(var t in tickets)
            {
                if(t.FK_SubscriptionId != null)
                {
                    _repository.IncreaseSessionsCount((int)t.FK_SubscriptionId);
                }
                _repository.DeleteTicket(t.Id);
            }
            _repository.DeleteSession(sessionid);
            return new EmptyResult();
        }
    }
}

WebApplication1/ViewComponents/GenreSelViewComponent.cs
using Cinema.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class GenreSelViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public GenreSelViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = _repo.GetGenres();
            var res = genres.ToList();
            res.Insert(0, new DataModels.Genre { Id = 0, Name = "None" });
            return View("_GenreSel.cshtml", res);
        }
    }
}

WebApplication1/ViewComponents/GenreSelectorViewComponent.cs
using Cinema.Contracts;
using Cinema.DataModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class GenreSelectorViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public GenreSelectorViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync(List<Genre> movieGenres)
        {
            var genres = _repo.GetGenres();
            var res = genres.ToList();
            foreach(var g in res)
            {
                if(movieGenres!= null && movieGenres.Any( x => x.Id == g.Id))
                {
                    g.Selected = true;
                }
            }
            return View("_GenreSelector.cshtml", res);
        }
    }
}

WebApplication1/ViewComponents/ProducerSelViewComponent.cs
using Cinema.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class ProducerSelViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public ProducerSelViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var producers = _repo.GetProducers();
            var res = producers.ToList();
            res.Insert(0, new DataModels.Producer { Id = 0, Name = "None" });
            return View("_ProducerSel.cshtml", res);
        }
    }
}

WebApplication1/Views/Movie/EditMovie.cshtml
@model Cinema.DataModels.Movie
@{
    ViewData["Title"] = "EditMovie";
}


<link href="~/css/EditComponents.css" rel="stylesheet" type="text/css" />

<form action="" method="post">
    <div>
        @* @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.Producers)
            *@
        <div>
            <label class="edit-label">Name:</label>
            <textarea asp-for="Name" class="edit-component" style="font-size:large;height:30px;">@Model.Name</textarea>
            <span class="edit-component" asp-validation-for="Name"></span>
        </div>
        <div>
            <label class="edit-label">Country:</label>
            <textarea asp-for="Country" class="edit-component" style="font-size:large;height:30px;">@Model.Country</textarea>
        </div>
        <div>
            <label class="edit-label">Release date:</label>
            <textarea name="Date" class="edit-component" style="font-size:large;height:30px;">@Model.ReleaseDate.ToString().Substring(0, 10)</textarea>
            <span class="edit-component" asp-validation-for="Date"></span>
        </div>
        <div>
            <label class="edit-label">Price:</label>
            <textarea asp-for="Price" class="edit-component" style="font-size:large;height:30px;">@Model.Price</textarea>
            <span class="edit-component" asp-validation-for="Price"></span>
        </div>
        <div>
            <label class="edit-label">Duration:</label>
            <textarea asp-for="Duration" class="edit-component" style="font-size:large;height:30px;">@Model.Duration.ToString()</textarea>
            <span class="edit-component" asp-validation-for="Duration"></span>
        </div>
        <div>
            <label>Producer:</label>
            <div>
                @await Component.InvokeAsync("ProducerSelector", new { movieProducers = Model.Producers })
            </div>
        </div>
        <div>
            <label>Genre:</label>
            <div>
                @await Component.InvokeAsync("GenreSelector", new {movieGenres = Model.Genres })
            </div>
            </div>
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="/movie/save">Save</button>
        <button class="btn btn-danger" type="submit" style="margin:30px" formaction="/movie/delete">Delete</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="/movie/cancel">Cancel</button>
    </div>
</form>

WebApplication1/Views/Movie/MovieList.cshtml
@model List<Cinema.DataModels.Movie>
@{
    ViewData["Title"] = "MovieList";
}



<table style="width:100%">
    <tr>
        <th>Name</th>
        <th>Country</th>
        <th>Release Date</th>
        <th>Genre</th>
        <th>Producer</th>
        <th>Duration</th>
    </tr>

    @foreach (var movie in Model)
    {
        <tr>
            <th>@movie.Name</th>
            <th>@movie.Country</th>
            <th>@movie.ReleaseDate.ToString().Substring(0, 10)</th>
            <th>@string.Join(",", movie?.Genres.Select(x => x.Name))</th>
            <th>@string.Join(",", movie.Producers?.Select(x => x.Name))</th>
            <th>@movie.Duration min.</th>
            <th>
                <a class="btn btn-default" asp-action="SearchByFilm" asp-controller="Session" asp-route-movieid="@movie.Id">Sessions</a>
            </th>
            @if (ViewBag.IsAdmin)
            {
                <th>
                    <a class="btn btn-default" asp-action="Add" asp-controller="Session" asp-route-movieid="@movie.Id">Add session</a>
                    <a class="btn btn-default" asp-action="Edit" asp-controller="Movie" asp-route-movieid="@movie.Id">Edit movie</a>
                </th>
            }
        </tr>
    }
</table>

WebApplication1/Views/Movie/SearchMovies.cshtml
@model Cinema.Models.SearchMoviesModel
@{
    ViewData["Title"] = "SearchMovies";
}

<link href="~/css/Shared.css" rel="stylesheet" type="text/css" />
<link href="~/css/SearchPostsFields.css" rel="stylesheet" type="text/css" />

<form asp-controller="Movie" asp-action="Search" method="post" id="SearchForm">
    <div class="search-div">
        <label class="search-label">Name:</label>
        <input asp-for="NameFirstLetters" />
    </div>
    <div>
        <label class="search-label">Genre:</label>
        <div class="search-div">
            <select asp-for="GenreId">
                @await Component.InvokeAsync("GenreSel")
            </select>
        </div>
    </div>
    <div>
        <label class="search-label">Producer:</label>
        <div class="search-div">
            <select asp-for="ProducerId">
                @await Component.InvokeAsync("ProducerSel")
            </select>
        </div>
    </div>
    <div>
        <button class="btn btn-success" style="margin:20px;" type="submit">Search</button>
    </div>
</form>

WebApplication1/Views/Movie/_GenreSel.cshtml
@model List<Cinema.DataModels.Genre>
@{
    ViewData["Title"] = "_GenreSelector";
}

@foreach (var genre in Model)
{
    <option value="@genre.Id">@genre.Name</option>
}

WebApplication1/Views/Movie/_GenreSelector.cshtml
@model List<Cinema.DataModels.Genre>
@{
    ViewData["Title"] = "_GenreSelector";
}

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript" type="text/javascript">
    $(document).on("click", "[type='checkbox']", function (e) {
        if (this.checked) {
            $(this).attr("value", "true");
        } else {
            $(this).attr("value", "false");
        }
    });
</script>

@for (int i = 0; i < Model.Count(); ++i)
{
    var name = "Genres[" + i + "].Selected";
    var name2 = "Genres[" + i + "].Id";
    <input type="checkbox" @(Model[i].Selected ? "checked" : "") name="@name" value="@Model[i].Selected" />
    <input type="hidden" name="@name2" value="@Model[i].Id" />
    <label>@Model[i].Name</label>
}

WebApplication1/Views/Movie/_ProducerSel.cshtml
@model List<Cinema.DataModels.Producer>
@{
    ViewData["Title"] = "_ProducerSelector";
}

@foreach (var producer in Model)
{
    <option value="@producer.Id">@producer.Name</option>
}

WebApplication1/Views/Movie/_ProducerSelector.cshtml
@model List<Cinema.DataModels.Producer>
@{
    ViewData["Title"] = "_ProducerSelector";
}

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript" type="text/javascript">
    $(document).on("click", "[type='checkbox']", function (e) {
        if (this.checked) {
            $(this).attr("value", "true");
        } else {
            $(this).attr("value", "false");
        }
    });
</script>

@for (int i = 0; i < Model.Count(); ++i)
{
    var name = "Producers[" + i + "].Selected";
    var name2 = "Producers[" + i + "].Id";
    <input type="checkbox" @(Model[i].Selected ? "checked" : "") name="@name" value="@Model[i].Selected" />
    <input type="hidden" name="@name2" value="@Model[i].Id" />
    <label>@Model[i].Name</label>
}

@*
@foreach (var producer in Model)
{
    <option value="@producer.Id">@producer.Name</option>
}
    *@