WebApplication1/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization;
using Cinema.Contracts;
using Cinema.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class TicketController : Controller
    {   
        IRepository _repo;
        public TicketController(IRepository repository)
        {
            _repo = repository;
        }

        [HttpGet]
        public IActionResult BuyTicket(int sessionid)
        {
            ViewBag.userid = User.GetId();
            var ticket = new Ticket();
            ticket.FK_SessionID = sessionid;
            return View("PurchaseTicket", ticket);
        }

        [HttpPost]
        public IActionResult Save(Ticket ticket)
        {
            ticket.FK_UserId = User.GetId();
            
            var price = _repo.CalculatePrice(ticket.FK_SessionID, ticket.FK_PlaceID);
            ticket.Price = price;
            
            if (ticket.FK_SubscriptionId != 0 && ticket.FK_SubscriptionId != null)
            {
                _repo.DecreaseSessionsCount((int)ticket.FK_SubscriptionId);
            }
            else 
                ticket.FK_SubscriptionId = -1;

            _repo.AddTicket(ticket);
            return RedirectToAction("Search", "Movie");

        }

        [HttpPost]
        public IActionResult Delete(int ticketid)
        {
            var subscrId = _repo.GetSubscriptionByTicketId(ticketid);
            if(subscrId != null)
            {
                _repo.IncreaseSessionsCount((int)subscrId);
            }
            _repo.DeleteTicket(ticketid);
            return RedirectToAction("Index", "UserAccount", new { userid = User.GetId()});
        }
    }
}

WebApplication1/ViewComponents/RowAndPlaceSelectorViewComponent.cs
using Cinema.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class RowAndPlaceSelectorViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public RowAndPlaceSelectorViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync(int sessionId)
        {
            var places = _repo.GetFreePlacesForSession(sessionId);
            return View("_RowAndPlaceSelector.cshtml", places.ToList());
        }
    }
}

WebApplication1/ViewComponents/SubscriptionSelectorViewComponent.cs
using Cinema.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class SubscriptionSelectorViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public SubscriptionSelectorViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync(int userid)
        {
            var subscriptions = _repo.GetUserSubscriptions(userid);
            var res = subscriptions.ToList();
            res.Insert(0, new DataModels.Subscription { Id = 0 });
            return View("~/Views/Ticket/_SubscriptionSelector.cshtml", res);
        }
    }
}

WebApplication1/Views/Ticket/PurchaseTicket.cshtml
@model Cinema.DataModels.Ticket
@{
    ViewData["Title"] = "PurchaseTicket";
}

@*<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript" type="text/javascript">
    //$(document).ready(function () {
    //    $("#TicketForm").submit(function (eventObj) {

    //        var rowAndPlace = document.getElementById('RowPlaceSelector').nodeValue
    //        var res = rowAndPlace.split(" ");
    //        addRowAndPlaceToForm(res[0], res[1])
    //        return true;
    //    });
    //}

    //function addRowAndPlaceToForm(row, place) {

    //    $("#TicketForm").append(
    //        '<input type="hidden" name="Row" value="' + row + '"/>' +
    //        '<input type="hidden" name="Place" value="' + place + '"/>');
    //};

</script>*@

<link href="~/css/EditComponents.css" rel="stylesheet" type="text/css" />

<form action="" method="post" id="TicketForm">
    <div>
        @Html.HiddenFor(m => m.FK_SessionID)
        <div style="margin:10px;">
            <label>Choose subscription</label>
            <select asp-for="FK_SubscriptionId">
                @await Component.InvokeAsync("SubscriptionSelector", new { userid = ViewBag.userid })
            </select>
        </div>

        <div>
            <label>Choose place</label>
            <select asp-for="FK_PlaceID">
                @await Component.InvokeAsync("RowAndPlaceSelector", new { sessionid = Model.FK_SessionID })
            </select>
        </div>
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="/ticket/save">Save</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="/ticket/cancel">Cancel</button>
    </div>
</form>

WebApplication1/Views/Ticket/_RowAndPlaceSelector.cshtml
@model List<Cinema.DataModels.Place>
@{
    ViewData["Title"] = "_RowAndPlaceSelector";
}

@foreach(var place in Model)
{
    <option value="@place.Id">Row: @place.Row Place: @place.PlaceNumber</option>
}

WebApplication1/Views/Ticket/_SubscriptionSelector.cshtml
@model List<Cinema.DataModels.Subscription>
@{
    ViewData["Title"] = "_SubscriptionSelector";
}

@foreach (var subscr in Model)
{
    @if (subscr.Id == 0)
    {
        <option value="@subscr.Id">None</option>
    }
    else
    {
        <option value="@subscr.Id">@subscr.Balance @subscr.Price</option>
    }

}