WebApplication1/Controllers/MovieController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Cinema.DataModels;
using Cinema.Contracts;
using Cinema.Models;
using System;
using System.Collections.Generic;

namespace Cinema.Controllers
{
    public class MovieController : Controller
    {
        private readonly IRepository _repo;
        public MovieController(IRepository repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("EditMovie", new Movie());
        }

        [HttpGet]
        public IActionResult Edit(int movieId)
        {
            var movie = _repo.GetMovieById(movieId);
            return View("EditMovie", movie);
        }

        [HttpPost]
        public IActionResult Save(Movie movie, string producersStr, List<Genre> test)
        {

            if(!ModelState.IsValid)
            {
                return View("EditMovie", movie);
            }

            DateTime releasedate;
            var date = movie.Date?.Trim();
            try
            { 
                releasedate = new DateTime(Convert.ToInt32(date.Substring(6, 4)), Convert.ToInt32(date.Substring(3, 2)), Convert.ToInt32(date.Substring(0, 2)));
                if (releasedate < DateTime.Now)
                    throw new Exception();
            }
            catch
            {
                ModelState.AddModelError("Date", "Entered release date is not valid date");
                return View("EditMovie", movie);
            }

            movie.ReleaseDate = releasedate;
            movie.Genres = movie.Genres.Where(x => x.Selected).ToList();
            
            if(!string.IsNullOrWhiteSpace(producersStr))
            {
                var producers = producersStr.Split(',', StringSplitOptions.RemoveEmptyEntries);
                for(int i = 0; i < producers.Length; ++ i)
                {
                    if(movie.Producers.Any(x => x.Name == producers[i]))
                    {
                        continue;
                    }

                    var prod = _repo.GetProducerIdByName(producers[i].Trim());
                    if (prod == null)
                    {
                        prod = _repo.AddProducer(producers[i].Trim());
                    }

                    movie.Producers.Add(new Producer { Id = (int)prod, Name = producers[i] });
                }
            }

            
            if(movie.Id > 0)
            {
                _repo.UpdateMovie(movie);
            }
            else
            {
                _repo.AddMovie(movie);
            }
            return View("SearchMovies");
        }

        [HttpPost]
        public IActionResult Delete(Movie movie)
        {
            var tickets = _repo.GetMovieTickets(movie.Id);
            foreach(var t in tickets)
            {
                if(t.FK_SubscriptionId != null)
                {
                    _repo.DeleteSubscription((int)t.FK_SubscriptionId);
                }
                _repo.DeleteTicket(t.Id);
            }

            var sessions = _repo.GetSessionsByMovie(movie.Id);
            foreach(var s in sessions)
            {
                _repo.DeleteSession(s.Id);
            }
            _repo.DeleteMovie(movie.Id);
            return View("SearchMovies");
        }

        [HttpGet]
        public IActionResult Search()
        {
            return View("SearchMovies", new SearchMoviesModel());
        }

        [HttpPost]
        public IActionResult Cancel()
        {
            return RedirectToAction("Search");
        }

        [HttpPost]
        public IActionResult Search(SearchMoviesModel model)
        {
            ViewBag.IsAdmin = User.HasClaim("AccessType", "Admin");
            IEnumerable<Movie> movies;
            if (ViewBag.IsAdmin)
            { movies = _repo.GetMoviesByNameGenreOrProducer(model.NameFirstLetters, model.GenreId, model.ProducerId).ToList(); }
            else
            {
                movies = _repo.GetCurrentMovies(DateTime.Now, model.NameFirstLetters, model.GenreId, model.ProducerId).ToList();
            }
            return View("MovieList", movies);
        }
    }
}

WebApplication1/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cinema.Contracts;
using Cinema.DataModels;
using Cinema.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class SessionController : Controller
    {
        private enum TimeAllowance
        {
            Morning = 3,
            Day = 4,
            Evening = 5
        }

        private int GetTimeAllowance(DateTime dateTime)
        {
            if (dateTime.TimeOfDay.Hours < 14)
            {
                return (int)TimeAllowance.Morning;
            }
            else if (dateTime.TimeOfDay.Hours < 18)
            {
                return (int)TimeAllowance.Day;
            }
            return (int)TimeAllowance.Evening;
        }

        IRepository _repository;
        public SessionController(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Add(int movieid)
        {
            return View("AddSession", new Session { MovieId = movieid });
        }

        [HttpPost]
        public IActionResult Save(Session session)
        {
            session.Price = _repository.GetPriceByTimeAllowance(GetTimeAllowance(session.StartTime));
            _repository.AddSession(session);
            return RedirectToAction("Search");
        }

        [HttpGet]
        public IActionResult Search()
        {
            return View("SearchSessions", new SearchSessionsModel());
        }

        [HttpPost]
        public IActionResult Search(SearchSessionsModel searchSessionsModel)
        {
            ViewBag.IsAdmin = User.HasClaim("AccessType", "Admin");
            if(searchSessionsModel.Date == null)
            {
                return View("SessionList", _repository.GetAllSessions());
            }
            return View("SessionList", _repository.GetSessionsByDate(searchSessionsModel.Date.Trim()));
        }

        [HttpGet]
        public IActionResult SearchByFilm(int movieId)
        {
            ViewBag.IsAdmin = User.HasClaim("AccessType", "Admin");
            return View("SessionList", _repository.GetSessionsByMovie(movieId));
        }

        [HttpGet]
        public IActionResult Cancel()
        {
            return RedirectToAction("Search");
        }

        [HttpPost]
        public IActionResult Delete(int sessionid)
        {
            var tickets = _repository.GetSessionTickets(sessionid);
            foreach(var t in tickets)
            {
                if(t.FK_SubscriptionId != null)
                {
                    _repository.IncreaseSessionsCount((int)t.FK_SubscriptionId);
                }
                _repository.DeleteTicket(t.Id);
            }
            _repository.DeleteSession(sessionid);
            return new EmptyResult();
        }
    }
}

WebApplication1/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization;
using Cinema.Contracts;
using Cinema.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class TicketController : Controller
    {   
        IRepository _repo;
        public TicketController(IRepository repository)
        {
            _repo = repository;
        }

        [HttpGet]
        public IActionResult BuyTicket(int sessionid)
        {
            ViewBag.userid = User.GetId();
            var ticket = new Ticket();
            ticket.FK_SessionID = sessionid;
            return View("PurchaseTicket", ticket);
        }

        [HttpPost]
        public IActionResult Save(Ticket ticket)
        {
            ticket.FK_UserId = User.GetId();
            
            var price = _repo.CalculatePrice(ticket.FK_SessionID, ticket.FK_PlaceID);
            ticket.Price = price;
            
            if (ticket.FK_SubscriptionId != 0 && ticket.FK_SubscriptionId != null)
            {
                _repo.DecreaseSessionsCount((int)ticket.FK_SubscriptionId);
            }
            else 
                ticket.FK_SubscriptionId = -1;

            _repo.AddTicket(ticket);
            return RedirectToAction("Search", "Movie");

        }

        [HttpPost]
        public IActionResult Delete(int ticketid)
        {
            var subscrId = _repo.GetSubscriptionByTicketId(ticketid);
            if(subscrId != null)
            {
                _repo.IncreaseSessionsCount((int)subscrId);
            }
            _repo.DeleteTicket(ticketid);
            return RedirectToAction("Index", "UserAccount", new { userid = User.GetId()});
        }
    }
}

WebApplication1/ViewComponents/HallSelectorViewComponent.cs
using Cinema.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class HallSelectorViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public HallSelectorViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var halls = _repo.GetAllHalls();
            return View("_HallSelector.cshtml", halls.ToList());
        }
    }
}

WebApplication1/Views/Session/AddSession.cshtml
@model Cinema.DataModels.Session
@{
    ViewData["Title"] = "AddSession";
}
<link href="~/css/EditComponents.css" rel="stylesheet" type="text/css" />

<form action="" method="post">
    <div>
        @Html.HiddenFor(m => m.MovieId)
        <div>
            <label class="edit-label">Date and time:</label>
            <textarea asp-for="StartTime" class="edit-component" style="font-size:large;height:100px;"></textarea>
            <span class="edit-component" asp-validation-for="StartTime"></span>
        </div>

        <div>
            <label class="edit-label">Hall:</label>
            <select asp-for="FK_HallId">
                @await Component.InvokeAsync("HallSelector")
            </select>
        </div>
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="/session/save">Save</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="/session/cancel">Cancel</button>
    </div>
</form>

WebApplication1/Views/Session/SearchSessions.cshtml
@model Cinema.Models.SearchSessionsModel
@{
    ViewData["Title"] = "SearchSessions";
}

<link href="~/css/Shared.css" rel="stylesheet" type="text/css" />
<link href="~/css/SearchPostsFields.css" rel="stylesheet" type="text/css" />
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript" type="text/javascript">
    //function Search() {
    //    var value = document.getElementById('DateInput').value;
    //    $.post("/session/search?date=" + value, function (template) {
    //        $("#sessions").html(template);
    //    });
    //};
</script>

<form method="post" asp-controller="Session" asp-action="Search">
<div class="search-div">
    <label class="search-label">Date:</label>
    <input id="DateInput" name="Date"/>
</div>

<div class="search-div">
    <button class="btn btn-success">Search</button>
</div>
    </form>

@*<div id="sessions">
    @{ Html.RenderPartial("SessionList", Model.Sessions); }
</div>*@

WebApplication1/Views/Session/SessionList.cshtml
@model List<Cinema.DataModels.Session>
@{
    ViewData["Title"] = "SessionList";
}

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript" type="text/javascript">
    function deleteSession(id) {
        $.post("/session/delete?sessionid=" + id);
        var session = document.getElementById("session" + id);
        session.parentNode.removeChild(session);
    };
</script>

<table style="width:100%">
    <a class="btn btn-default" asp-controller="Movie" asp-action="Search">Back</a>
    <tr>
        <th>Movie Name</th>
        <th>Dueation</th>
        <th>Date and time</th>
    </tr>

    @foreach (var session in Model)
    {
        var id = "session" + session.Id;
        <tr id="@id">
            <th>@session.MovieName</th>
            <th>@session.Duration min.</th>
            <th>@session.StartTime.ToString()</th>

            @if (ViewBag.IsAdmin)
            {
                <th>
                    <button class="btn btn-default" onclick="deleteSession(@session.Id)">Delete</button>
                </th>
            }
            else if(session.StartTime >= DateTime.Now)
            {
                <th>
                    <a class="btn btn-default" asp-action="BuyTicket" asp-controller="Ticket" asp-route-sessionid="@session.Id">Buy Ticket</a>
                </th>
            }
        </tr>
    }
   
</table>

WebApplication1/Views/Session/_HallSelector.cshtml
@model List<int>
@{
    ViewData["Title"] = "_HallSelector";
}

@foreach (var hall in Model)
{
    <option value="@hall">@hall</option>
}