WebApplication1/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization;
using Cinema.Contracts;
using Cinema.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class SubscriptionController : Controller
    {
        IRepository _repo;
        public SubscriptionController(IRepository repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Purchase()
        {
            return View("PurchaseSubscription", new Subscription());
        }

        [HttpPost]
        public IActionResult Save(Subscription subscription, string typeInfo)
        {
            var v = typeInfo.Split('#');
            var id = Convert.ToInt32(v[0]);
            var price = Convert.ToDouble(v[1]);
            var amount = Convert.ToInt32(v[2]);
            subscription.FK_UserId = User.GetId();
            subscription.FK_SubscriptionTypeId = id;
            subscription.Price = price;
            subscription.AllSessionsAmount = amount;
            subscription.Balance = amount;

            _repo.AddSubscription(subscription);
            return RedirectToAction("Index", "UserAccount", new { userid= User.GetId() });

        }
        [HttpGet]
        public IActionResult Manage()
        {
            var types = _repo.GetSubscriptionTypes();
            return View("SubscrTypes", types);
        }

        [HttpPost]
        public IActionResult Return(int subscrid)
        {
            _repo.DeleteSubscription(subscrid);
            return new EmptyResult();
        }

        [HttpPost]
        public IActionResult DeleteType(int subscrid)
        {
            _repo.DeleteSubscriptionType(subscrid);
            return new EmptyResult();
        }

        [HttpGet]
        public IActionResult AddType()
        {
            var type = new SubscriptionType();
            return View("AddSubscrType", type);
        }

        [HttpPost]
        public IActionResult SaveType(SubscriptionType type)
        {
            _repo.AddSubscriptionType(type);
            return RedirectToAction("Manage");
        }

        [HttpPost]
        public IActionResult CancelType()
        {
            return RedirectToAction("Manage");
        }

        [HttpPost]
        public IActionResult Cancel()
        {
            return RedirectToAction("MyAccount", "UserAccount");
        }
    }
}

WebApplication1/ViewComponents/SubscriptionTypeSelectorViewComponent.cs
using Cinema.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.ViewComponents
{
    public class SubscriptionTypeSelectorViewComponent : ViewComponent
    {
        private readonly IRepository _repo;
        public SubscriptionTypeSelectorViewComponent(IRepository repo)
        {
            _repo = repo;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var types = _repo.GetSubscriptionTypes();
            return View("_SubscriptionTypeSelector.cshtml", types.ToList());
        }
    }
}

WebApplication1/Views/Subscription/AddSubscrType.cshtml
@model Cinema.DataModels.SubscriptionType

<link href="~/css/EditComponents.css" rel="stylesheet" type="text/css" />

<form action="" method="post">
    <div>
        <div>
            <label class="edit-label">Price:</label>
            <textarea asp-for="Price" class="edit-component" style="font-size:large;height:100px;"></textarea>
        </div>

        <div>
            <label class="edit-label">Sessions amount:</label>
            <textarea asp-for="SessionCount" class="edit-component" style="font-size:large;height:100px;"></textarea>
        </div>
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="/subscription/savetype">Save</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="/subscription/canceltype">Cancel</button>
    </div>
</form>

WebApplication1/Views/Subscription/PurchaseSubscription.cshtml
@model Cinema.DataModels.Subscription
@{
    ViewData["Title"] = "PurchaseSubscription";
}

<link href="~/css/Shared.css" rel="stylesheet" type="text/css" />
<link href="~/css/SearchPostsFields.css" rel="stylesheet" type="text/css" />

<form action="" method="post">
    <div>
        <div class="search-div">
            <select name="typeInfo">
                @await Component.InvokeAsync("SubscriptionTypeSelector")
            </select>
        </div>
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="/subscription/save">Save</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="/subscription/cancel">Cancel</button>
    </div>
</form>

WebApplication1/Views/Subscription/SubscrTypes.cshtml
@model List<Cinema.DataModels.SubscriptionType>

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript" type="text/javascript">

    function deleteSubscr(id) {
        $.post("/subscription/deletetype?subscrid=" + id);
        var s = document.getElementById("subscr" + id);
        s.parentNode.removeChild(s);
    };
</script>

<table style="width:100%">
    <tr>
        <th>Price</th>
        <th>Sessions amount</th>
    </tr>

    @foreach (var type in Model)
    {
        var id = "subscr" + type.Id;
        <tr id="@id">
            <th>@type.Price</th>
            <th>@type.SessionCount</th>

            <th>
                <button class="btn btn-default"  onclick="deleteSubscr(@type.Id)">Delete type</button>
            </th>
        </tr>
    }

    <tr>
        <th>
            <a class="btn btn-default" asp-action="AddType" asp-controller="Subscription">Add type</a>
        </th>
    </tr>

</table>

WebApplication1/Views/Subscription/_SubscriptionTypeSelector.cshtml
@model List<Cinema.DataModels.SubscriptionType>
@{
    ViewData["Title"] = "_SubscriptionTypeSelector";
}

@foreach(var type in Model)
{
    <option value="@string.Join("#", type.Id, type.Price, type.SessionCount)">Price: @type.Price Sessions amount: @type.SessionCount </option>
}